/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/CoinsLeaderboard")]
    [LuaRegisterType(0x8e347eeaec79be44, typeof(LuaBehaviour))]
    public class CoinsLeaderboard : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "82c600bc725c7c749847d6b59bc2d313";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_LeaderboardTitle = "Leaderboard";
        [SerializeField] public System.Double m_UpdateInterval = 1;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_LeaderboardTitle),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_UpdateInterval),
                CreateSerializedProperty(_script.GetPropertyAt(2), null),
                CreateSerializedProperty(_script.GetPropertyAt(3), null),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/CoinsLeaderboard/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
