/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/Coins")]
    [LuaRegisterType(0x50972cf4a4489a2d, typeof(LuaBehaviour))]
    public class Coins : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "49394e8b7e11f9b48a03ad95c2c41d59";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String _id = "";
        [SerializeField] public System.Double m_Amount = 1;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _id),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_Amount),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/Coins/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
