/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/CoinCollectorScript")]
    [LuaRegisterType(0xd36a77114e516dd4, typeof(LuaBehaviour))]
    public class CoinCollectorScript : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "3256fecbdab993743bca6a863e6032d9";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double m_Amount = 1;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_Amount),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/CoinCollectorScript/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
