/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/CoinsManager")]
    [LuaRegisterType(0x1440eab511baa3c4, typeof(LuaBehaviour))]
    public class CoinsManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "a3294022af59651428cd614340d2556a";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double m_InitialCoinCount = 25;
        [SerializeField] public UnityEngine.GameObject m_CoinPrefab = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_InitialCoinCount),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_CoinPrefab),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/CoinsManager/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
