/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/CoinsSpawner")]
    [LuaRegisterType(0x1440eab511baa3c4, typeof(LuaBehaviour))]
    public class CoinsSpawner : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "a3294022af59651428cd614340d2556a";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_coinPrefab = default;
        [SerializeField] public System.Double m_maxCoinWorth = 50;
        [SerializeField] public System.Double m_minCoinScale = 0.3;
        [SerializeField] public System.Double m_maxCoinScale = 5;
        [SerializeField] public UnityEngine.Vector3 m_floorScale = new Vector3(10f, 0f, 10f);
        [SerializeField] public UnityEngine.Vector3 m_floorPos = new Vector3(0f, 0.5f, 0f);
        [SerializeField] public System.Double m_syncSceneTimer = 5;
        [SerializeField] public System.Double m_spawnCoinsTimer = 10;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_coinPrefab),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_maxCoinWorth),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_minCoinScale),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_maxCoinScale),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_floorScale),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_floorPos),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_syncSceneTimer),
                CreateSerializedProperty(_script.GetPropertyAt(7), m_spawnCoinsTimer),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/CoinsSpawner/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
