/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/OpenClosetObject")]
    [LuaRegisterType(0x4d7dcfd61efb63e6, typeof(LuaBehaviour))]
    public class OpenClosetObject : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "0cdf64a386bfd984bb0be43707d3ee17";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("If true, the player's own closet inventory will be included in this closet.")]
        [SerializeField] public System.Boolean _includePlayerClosetInventory = true;
        [Tooltip("Clothing Collections that will be included in the closet which provide additional clothing. Create one from the menu Assets->Create->Highrise->Clothing Collection")]
        [SerializeField] public System.Collections.Generic.List<Highrise.ClothingCollection> _includedClothingCollections = default;
        [SerializeField] public System.Boolean _useCustomStartingOutfit = false;
        [Tooltip("Starting closet outfit to use when opening the closet.")]
        [SerializeField] public Highrise.ClothingCollection _startingClosetOutfit = default;
        [Tooltip("Should default to the first tab, excluding the All tab, in the closet.")]
        [SerializeField] public System.Boolean _defaultToFirstTab = false;
        [Header("Title Settings")]
        [SerializeField] public System.String _closetTitle = "Dress Up";
        [SerializeField] public System.String _saveButtonText = "Save";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _includePlayerClosetInventory),
                CreateSerializedProperty(_script.GetPropertyAt(1), _includedClothingCollections),
                CreateSerializedProperty(_script.GetPropertyAt(2), _useCustomStartingOutfit),
                CreateSerializedProperty(_script.GetPropertyAt(3), _startingClosetOutfit),
                CreateSerializedProperty(_script.GetPropertyAt(4), _defaultToFirstTab),
                CreateSerializedProperty(_script.GetPropertyAt(5), _closetTitle),
                CreateSerializedProperty(_script.GetPropertyAt(6), _saveButtonText),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/OpenClosetObject/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
