/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/PetCharacterController")]
    [LuaRegisterType(0x5a9f847683977bd, typeof(LuaBehaviour))]
    public class PetCharacterController : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "c5c51b90893ddc5419e9641764c16452";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject _characterPrefab = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _characterPrefab),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/PetCharacterController/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
