/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/PlayMusic")]
    [LuaRegisterType(0x62641fc8d7883e7e, typeof(LuaBehaviour))]
    public class PlayMusic : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "c5419f004d9c2db448a8407bd5693e6e";
        public override string ScriptGUID => s_scriptGUID;

        [Header("Music URL Settings")]
        [SerializeField] public System.Boolean _playMusicFromURL = false;
        [Tooltip("URL of the music to play. If set, this will override the Audio Shader.")]
        [SerializeField] public System.String _musicURL = "";
        [Header("Music Clip Settings")]
        [Tooltip("Audio shader music to play. To create an Audio Shader, right click an audio file then go to Create->Highrise->Audio->Audio Shader")]
        [SerializeField] public Highrise.AudioShader _musicAudioShader = default;
        [SerializeField] public System.Boolean _loopMusic = true;
        [Header("Common Music Settings")]
        [Range(0,1)]
        [SerializeField] public System.Double _volume = 1;
        [SerializeField] public System.Boolean _fadeIn = true;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _playMusicFromURL),
                CreateSerializedProperty(_script.GetPropertyAt(1), _musicURL),
                CreateSerializedProperty(_script.GetPropertyAt(2), _musicAudioShader),
                CreateSerializedProperty(_script.GetPropertyAt(3), _loopMusic),
                CreateSerializedProperty(_script.GetPropertyAt(4), _volume),
                CreateSerializedProperty(_script.GetPropertyAt(5), _fadeIn),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/PlayMusic/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
