/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/ScaleObject")]
    [LuaRegisterType(0x2907db16af68c8ce, typeof(LuaBehaviour))]
    public class ScaleObject : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "0fbf1c513f0fed249bc99454b012d0c6";
        public override string ScriptGUID => s_scriptGUID;

        [Tooltip("The object to scale. If left empty, the object this script is attached to will be scaled.")]
        [SerializeField] public UnityEngine.Transform _objectToScale = default;
        [SerializeField] public UnityEngine.Vector3 _startScale = new Vector3(1f, 1f, 1f);
        [SerializeField] public UnityEngine.Vector3 _endScale = new Vector3(1f, 1f, 1f);
        [Tooltip("The duration of the scale in seconds to reach the destination.")]
        [SerializeField] public System.Double _durationInSeconds = 3;
        [Tooltip("If true, the scale will loop back to the start after reaching the destination and then repeat forever.")]
        [SerializeField] public System.Boolean _loop = true;
        [Tooltip("If true, the scale will be smooth when starting and arriving at the destination.")]
        [SerializeField] public System.Boolean _smoothScale = true;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _objectToScale),
                CreateSerializedProperty(_script.GetPropertyAt(1), _startScale),
                CreateSerializedProperty(_script.GetPropertyAt(2), _endScale),
                CreateSerializedProperty(_script.GetPropertyAt(3), _durationInSeconds),
                CreateSerializedProperty(_script.GetPropertyAt(4), _loop),
                CreateSerializedProperty(_script.GetPropertyAt(5), _smoothScale),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/ScaleObject/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
