/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/TeleporterObject")]
    [LuaRegisterType(0x1f633be2a0ae7ee6, typeof(LuaBehaviour))]
    public class TeleporterObject : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "c5017d8fcbef5d2409a2ce6186f79c31";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Transform m_destination = default;
        [SerializeField] public System.Boolean m_teleportCharactersOnly = true;
        [Tooltip("Whether to play a sound when using the teleporter, local player only")]
        [SerializeField] public System.Boolean m_playSound = false;
        [Tooltip("The audio shader to play when teleporting.")]
        [SerializeField] public Highrise.AudioShader m_soundToPlay = default;
        [Tooltip("Whether to play a particle effect when using the teleporter.")]
        [SerializeField] public System.Boolean m_playParticleEffect = true;
        [Tooltip("The prefab containing the particle effect to play at the destination after teleporting")]
        [SerializeField] public UnityEngine.GameObject m_teleportParticles = default;
        [Tooltip("Whether to move the camera to your character after teleporting.")]
        [SerializeField] public System.Boolean m_resetCameraAfterTeleport = true;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_destination),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_teleportCharactersOnly),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_playSound),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_soundToPlay),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_playParticleEffect),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_teleportParticles),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_resetCameraAfterTeleport),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/TeleporterObject/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
